name: Jekyll Build

on:
  push:
    branches:
      - main  # Ganti dengan nama cabang yang Anda gunakan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7  # Versi Ruby yang akan digunakan
      id: ruby

    - name: Install Jekyll and dependencies
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install
      env:
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
