name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main  # Ganti dengan nama cabang yang sesuai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7  # Ganti dengan versi Ruby yang sesuai

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
      env:
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3

    - name: Build Jekyll site
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

